apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: logging
spec:
  general:
    serviceName: "opensearch-cluster"
    version: 1.3.1
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    opensearchCredentialsSecret:
      name: dashboards-credentials-secret
  confMgmt:
    smartScaler: true
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "1Gi"
      roles:
        - "cluster_manager"
        - "data"
        - "ingest"
  users:
    - name: fluentbit
      passwordFrom:
        name: fluentbit-password
        key: password
      backendRoles:
        - kibana_user
      roles:
        - fluentbit
  roles:
    - name: fluentbit
      clusterPermissions:
        - cluster_composite_ops
        - cluster_monitor
      indexPermissions:
        - indexPatterns:
            - audit-*
            - container-*
            - access-*
          allowedActions:
            - create_index
            - index
            - write
  settings:
    security:
      config:
        adminCredentialsSecret:
          name: admin-credentials-secret
        securityConfigSecret:
          name: securityconfig-secret
      tls:
        transport:
          generate: true
        http:
          generate: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - opensearch.koellgma.de
    tls:
      - secretName: opensearch-tls
        hosts:
          - opensearch.koellgma.de
  serviceMonitor:
    enabled: false
    labels:
      release: prometheus-stack
  indexTemplates:
    global:
      defaultTemplates:
        access: true
        audit: true
        container: true
