apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://she-informationstechnologie.github.io/charts/
    chart: logging-opensearch
    targetRevision: 1.2.1
    helm:
      values: |
        opensearch:
          settings:
            security:
              tls:
                http:
                  generate: true
                  secret:
                    name: opensearch-tls
            nodePools:
              - component: nodes
                replicas: 3
                diskSize: "5Gi"
                persistence:
                  pvc:
                    accessModes:
                      - ReadWriteOnce
                    storageClass: standard
                nodeSelector:
                roles:
                  - "cluster_manager"
                  - "data"
                  - "ingest"
                pdb:
                  enable: true
                  maxUnavailable: 1
          ingress:
            enabled: true
            className: "nginx"
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: "letsencrypt-prod" 
            hosts:
              - host: opensearch.koellgma.de
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - hosts:
                - opensearch.koellgma.de
          ismPolicies:
            defaultState: hot
            ismTemplate: 
              indexPatterns:
                - container
                - ".ds-container*"
              priority: 2
            states:
              - name: hot
                actions:
                  - replicaCount:
                      numberOfReplicas: 1
                transitions:
                  - stateName: warm
                    conditions:
                      minIndexAge: "2d"
              - name: warm
                actions:
                  - replicaCount:
                      numberOfReplicas: 1
                transitions:
                  - stateName: delete
                    conditions:
                      minIndexAge: "5d"
              - name: delete
                actions:
                  - delete: {}
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: logging
