apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
  namespace: logging
type: Opaque
stringData:
  internal_users.yml: |
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "2a$12$dJB5vciKah2WhthMQmGgdetHSuEVFHdhWr0J3e3QsF3L//zZeXfgC"
      reserved: true
      backend_roles:
      - "admin"
      description: "admin user"