---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: postgres-dbs
  namespace: argocd
spec:
  description: Databases roject
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
  - kind: '*'
    group: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db01
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
spec:
  project: databases
  source:
    repoURL: https://github.com/mkoellges/postgres.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
