apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mkoellges/argocd-ops.git
    targetRevision: HEAD
    path: bootstrap
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - PrunePropagationPolicy=foreground
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    - Replace=true
    - ServerSideApply=true