apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: argocd
spec:
  project: default
  source:
    chart: opensearch-operator
    repoURL: https://opensearch-project.github.io/opensearch-k8s-operator/
    targetRevision: 2.7.0
    helm:
      releaseName: opensearch-operator
      values: |
        persistence:
          storageClass: "Standard"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - opensearch.koellgma.de
          tls: 
            - secretName: opensearch-tls
              hosts:
                - opensearch.koellgma.de
        serviceMonitor:
          enabled: false
          labels:
            release: prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
