---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/mkoellges/argocd-demo-app.git
    targetRevision: HEAD
    path: example-app/overlay/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true