apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-credentials
  namespace: velero
stringData:
  cloud: |
    [default]
    aws_access_key_id=velero
    aws_secret_access_key=velero
type: Opaque
