controller:
  hostNetwork: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  replicaCount: 1
  metrics:
    service:
      annotations:
        ingressClassName: nginx
  nodeSelector:
    ingress : worker
