apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  source:
    repoURL: https://helm.min.io/
    chart: minio/minio
    targetRevision: 8.0.9
    helm:
      values: |
        persistence:
          storageClass: standard
          accessMode: ReadWriteOnce
          size: 100Gi
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - minio.koellgma.de
          tls:
            - secretName: minio-tls
              host: minio.koellgma.de
        buckets:
          - name: postgres
            policy: none
            purge: false
          - name: velero
            policy: none
            purge: false
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
      replace: true
    syncOptions:
      - CreateNamespace=true
