apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-1
  namespace: argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio-1
  source:
    repoURL: https://gitlab.com/she-ag/cgm/projects/therafox/v2/k8s-deployments.git
    path: argocd/stage/apps/minio-1
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
