apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: backup
  namespace: minio-1
spec:
  image: minio/minio:RELEASE.2023-08-31T15-31-16Z
  configuration:
    name: minio-configuration
  exposeServices:
    console: true
    minio: true
  users:
    - name: minio-replication-user
    - name: minio-pgbackrest-user
  externalCertSecret:
    - name: minio-tls
      type: cert-manager.io/v1alpha2
  pools:
    - name: pool-1
      servers: 3
      volumesPerServer: 3
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: cinder-rbd
      resources:
        requests:
          cpu: "0.5"
          memory: 128M
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                      - source
                  - key: v1.min.io/pool
                    operator: In
                    values:
                      - pool-1
